server:
  port: 80
  servlet:
    context-path: /

spring:
  application:
    name: consumer-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #配置Nacos地址
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    static-path-pattern: /**

server-url:
  nacos-user-server: http://cloud-payment-service



