server:
  port: 80

spring:
  application:
    name: consumer-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #配置Nacos地址

server-url:
  nacos-user-server: http://cloud-payment-service



